I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 114, in script
    S "Нет, кажется я ничего не находил"
Exception: Sayer 'S' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 114, in script
    S "Нет, кажется я ничего не находил"
  File "F:\renpy\renpy-8.2.1-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "F:\renpy\renpy-8.2.1-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "F:\renpy\renpy-8.2.1-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'S' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
novella 1.0
Fri May 24 00:54:58 2024
